name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: SERVICE_ACCOUNT

    steps:
    - uses: actions/checkout@v4
    
    # Set Current Date As Env Variable
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    # Set Repository Name As Env Variable
    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Run Tests Build
    - name: Run gradle tests
      run: ./gradlew test

    # Run Build Project
    - name: Build with Gradle
      run: ./gradlew build

    # Run Generate Android Test APK
    - name: Generate Android Test APK
      run: ./gradlew assembleAndroidTest

    # Run Instrumented Tests
    - name: Run Android tests on Firebase Test Lab
      uses: asadmansr/Firebase-Test-Lab-Action@v1.0
      with:
        arg-spec: 'android-device.yml:android-pixel-8'
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
